import type { Artwork } from "./types";

/**
 * PLACEHOLDER CONTENT — invented works for demonstration. Each entry generates
 * a deterministic placeholder image from `seed` + `palette` until you supply a
 * real `image`/`thumbnail`. See docs/ASSET_REPLACEMENT.md.
 */

// Reusable period labels (drive the archive's "period" filter).
const P = {
  founding: "Founding · 1719–1761",
  court: "Court · 1755–1799",
  lateCoast: "Late Coast · 1782–1828",
  indigo: "Indigo Years · 1778–1820",
  contemporary: "Contemporary · 2009–",
} as const;

export const artworks: Artwork[] = [
  // ---- Luminist Landscapes (Marrow / Reyne) ----
  {
    id: "a-tideline",
    slug: "the-tideline",
    title: "The Tideline",
    artistId: "marrow",
    year: "1731",
    medium: "Egg tempera on panel",
    dimensions: "16 × 22 cm",
    location: "Harbour Wing · cabinet 3",
    collectionId: "luminist",
    period: P.founding,
    description:
      "A thread of pale light held between wet sand and low cloud, the entire drama compressed into a single horizontal seam.",
    historicalContext:
      "One of the earliest surviving Marrow panels, painted the year she abandoned mapmaking for the flats north of Saltmeadow.",
    orientation: "landscape",
    seed: "tideline-01",
    palette: { from: "#E8C48A", via: "#C98B4B", to: "#7A3F1E", ink: 0.06 },
    alt: "A wide, low horizon of luminous pale gold where wet sand meets a band of soft grey cloud, painted in thin warm tempera.",
    relatedArtworkIds: ["a-saltmeadow-dawn", "a-low-water", "a-survey-haze"],
    featured: true,
  },
  {
    id: "a-saltmeadow-dawn",
    slug: "saltmeadow-dawn",
    title: "Saltmeadow, Dawn",
    artistId: "marrow",
    year: "1734",
    medium: "Egg tempera on panel",
    dimensions: "18 × 18 cm",
    location: "Harbour Wing · cabinet 3",
    collectionId: "luminist",
    period: P.founding,
    description:
      "The meadow reduced to three warm registers of light, the sun implied but never shown.",
    historicalContext:
      "Marrow returned to this exact view across two decades; the archive holds nine variations of the Saltmeadow dawn.",
    orientation: "square",
    seed: "saltmeadow-02",
    palette: { from: "#F0D6A0", via: "#D79A55", to: "#8A4A22", ink: 0.05 },
    alt: "A square study of a coastal meadow at dawn rendered in three warm horizontal bands of gold and amber light.",
    relatedArtworkIds: ["a-tideline", "a-first-light", "a-low-water"],
    featured: true,
  },
  {
    id: "a-low-water",
    slug: "low-water",
    title: "Low Water",
    artistId: "marrow",
    year: "1739",
    medium: "Egg tempera on panel",
    dimensions: "14 × 26 cm",
    location: "Study Room · drawer 11",
    collectionId: "luminist",
    period: P.founding,
    description:
      "A drained estuary at its lowest ebb, the mud holding more light than the sky above it.",
    historicalContext:
      "Notable for inverting the expected tonal order — ground brighter than air — a device later borrowed by Reyne.",
    orientation: "landscape",
    seed: "lowwater-03",
    palette: { from: "#DEC79A", via: "#A98A57", to: "#5E4A2C", ink: 0.09 },
    alt: "A long horizontal panel of an estuary at low tide, the pale reflective mudflats brighter than the muted sky.",
    relatedArtworkIds: ["a-tideline", "a-estuary", "a-sand-index"],
  },
  {
    id: "a-first-light",
    slug: "first-light",
    title: "First Light",
    artistId: "marrow",
    year: "1742",
    medium: "Silverpoint & tempera on panel",
    dimensions: "20 × 15 cm",
    location: "Harbour Wing · cabinet 4",
    collectionId: "luminist",
    period: P.founding,
    description:
      "A vertical study in which the first minute of daylight climbs the panel like water filling a glass.",
    historicalContext:
      "A rare upright composition; the silverpoint underdrawing remains visible where the tempera was left deliberately thin.",
    orientation: "portrait",
    seed: "firstlight-04",
    palette: { from: "#EBD3A6", via: "#C99A5C", to: "#7C4620", ink: 0.06 },
    alt: "A tall vertical painting where warm dawn light gradually brightens from a dark base to a luminous top edge.",
    relatedArtworkIds: ["a-saltmeadow-dawn", "a-survey-haze", "a-tideline"],
    featured: true,
  },
  {
    id: "a-survey-haze",
    slug: "survey-in-haze",
    title: "Survey, in Haze",
    artistId: "reyne",
    year: "1804",
    medium: "Watercolour & ink wash",
    dimensions: "24 × 34 cm",
    location: "Map Room · portfolio A",
    collectionId: "luminist",
    period: P.lateCoast,
    description:
      "A surveyor's grid dissolving into salt haze, measurement and mood held in uneasy balance.",
    historicalContext:
      "Reyne overlaid his working triangulation lines with wet washes, a gesture read as either honesty or sabotage.",
    orientation: "landscape",
    seed: "surveyhaze-05",
    palette: { from: "#C9CDB4", via: "#95A079", to: "#55603F", ink: 0.05 },
    alt: "A pale coastal watercolour crossed by faint surveyor's grid lines that fade into a soft grey-green haze.",
    relatedArtworkIds: ["a-sand-index", "a-estuary", "a-low-water"],
  },
  {
    id: "a-sand-index",
    slug: "sand-index",
    title: "Sand Index",
    artistId: "reyne",
    year: "1811",
    medium: "Bodycolour on grey paper",
    dimensions: "28 × 20 cm",
    location: "Map Room · portfolio A",
    collectionId: "luminist",
    period: P.lateCoast,
    description:
      "Nine swatches of shoreline sand catalogued like specimens, each labelled by the hour it was gathered.",
    historicalContext:
      "An early instance of the archival, systematic impulse that Livia Okonkwo would later inherit.",
    orientation: "portrait",
    seed: "sandindex-06",
    palette: { from: "#D6C9A8", via: "#A6906A", to: "#5E4E34", ink: 0.07 },
    alt: "A vertical sheet of nine rectangular sand-colour swatches arranged in a grid, each hand-labelled beneath.",
    relatedArtworkIds: ["a-survey-haze", "a-earth-index", "a-estuary"],
  },
  {
    id: "a-estuary",
    slug: "estuary",
    title: "Estuary",
    artistId: "reyne",
    year: "1819",
    medium: "Watercolour",
    dimensions: "22 × 40 cm",
    location: "Map Room · portfolio B",
    collectionId: "luminist",
    period: P.lateCoast,
    description:
      "The coastline gone entirely, replaced by reflected sky and the memory of a river's mouth.",
    historicalContext:
      "Reyne's late works abandon the shoreline; the archive treats Estuary as the bridge to the modern collection.",
    orientation: "landscape",
    seed: "estuary-07",
    palette: { from: "#BFC9C0", via: "#8399A0", to: "#455B62", ink: 0.06 },
    alt: "A very wide, near-abstract watercolour of pale reflected sky over water with no visible land.",
    relatedArtworkIds: ["a-survey-haze", "a-low-water", "a-same-quay"],
  },

  // ---- Coastal Nocturnes (Vael) ----
  {
    id: "a-lantern-quay",
    slug: "lantern-on-the-quay",
    title: "Lantern on the Quay",
    artistId: "vael",
    year: "1759",
    medium: "Oil on prepared linen",
    dimensions: "40 × 55 cm",
    location: "Dark Room · east wall",
    collectionId: "nocturnes",
    period: P.court,
    description:
      "A single lantern holds back an ocean of dark; everything the painting contains is negotiated at its edge.",
    historicalContext:
      "The keystone of the Nocturnes, built from more than thirty lamp-black glazes cured over a full year.",
    orientation: "landscape",
    seed: "lantern-08",
    palette: { from: "#2E3A57", via: "#1B2338", to: "#0A0D18", ink: 0.22 },
    alt: "A dark harbour at night with a single warm lantern glowing on a stone quay, its light fading into deep blue-black.",
    relatedArtworkIds: ["a-black-tide", "a-harbour-watch", "a-ninth-bell"],
    featured: true,
  },
  {
    id: "a-black-tide",
    slug: "black-tide",
    title: "Black Tide",
    artistId: "vael",
    year: "1766",
    medium: "Oil on prepared linen",
    dimensions: "45 × 45 cm",
    location: "Dark Room · east wall",
    collectionId: "nocturnes",
    period: P.court,
    description:
      "Water at its darkest hour, distinguishable from the sky only by the way it refuses to hold a reflection.",
    historicalContext:
      "Vael reportedly painted this square canvas entirely between the ninth and tenth bells of successive nights.",
    orientation: "square",
    seed: "blacktide-09",
    palette: { from: "#242E48", via: "#141A2C", to: "#080B14", ink: 0.24 },
    alt: "A near-black square nocturne where the boundary between dark sea and dark sky is almost imperceptible.",
    relatedArtworkIds: ["a-lantern-quay", "a-ninth-bell", "a-night-cloth"],
  },
  {
    id: "a-harbour-watch",
    slug: "harbour-watch",
    title: "Harbour Watch",
    artistId: "vael",
    year: "1771",
    medium: "Oil on prepared linen",
    dimensions: "38 × 50 cm",
    location: "Dark Room · south wall",
    collectionId: "nocturnes",
    period: P.court,
    description:
      "Two lanterns and the suggestion of a figure keeping the night's long, uneventful vigil.",
    historicalContext:
      "Infrared study has revealed a second figure Vael painted out — the watch was once a pair.",
    orientation: "landscape",
    seed: "harbourwatch-10",
    palette: { from: "#333E5A", via: "#1E2740", to: "#0C1020", ink: 0.2 },
    alt: "A nocturne of a harbour with two small warm lanterns and the faint silhouette of a standing figure in the dark.",
    relatedArtworkIds: ["a-lantern-quay", "a-black-tide", "a-ninth-bell"],
  },
  {
    id: "a-ninth-bell",
    slug: "the-ninth-bell",
    title: "The Ninth Bell",
    artistId: "vael",
    year: "1783",
    medium: "Oil on prepared linen",
    dimensions: "60 × 42 cm",
    location: "Dark Room · south wall",
    collectionId: "nocturnes",
    period: P.court,
    description:
      "The latest of the Nocturnes, in which the lantern has almost gone out and the dark is nearly complete.",
    historicalContext:
      "Painted in Vael's final decade; conservators believe the extreme darkness is intentional rather than degraded varnish.",
    orientation: "portrait",
    seed: "ninthbell-11",
    palette: { from: "#28324C", via: "#161C30", to: "#070A12", ink: 0.26 },
    alt: "A tall, extremely dark nocturne with a single dying ember of lantern light near the lower edge.",
    relatedArtworkIds: ["a-lantern-quay", "a-harbour-watch", "a-black-tide"],
  },

  // ---- Court Manuscripts (Serré) ----
  {
    id: "a-tide-charter",
    slug: "tide-charter",
    title: "Tide Charter",
    artistId: "serre",
    year: "1762",
    medium: "Gold leaf & gouache on vellum",
    dimensions: "30 × 21 cm",
    location: "Vellum Room · folio 2",
    collectionId: "manuscripts",
    period: P.court,
    description:
      "An official tide-table whose margins bloom with birds, fish and small storms the law never asked for.",
    historicalContext:
      "The document survives because of its function; it is studied for everything Serré added beyond it.",
    orientation: "portrait",
    seed: "tidecharter-12",
    palette: { from: "#EAD9B5", via: "#CFB073", to: "#8F6E33", ink: 0.05 },
    alt: "An illuminated vellum charter with columns of tide figures framed by gold and blue marginal decoration of birds and fish.",
    relatedArtworkIds: ["a-margin-storm", "a-silver-fish", "a-reed-hours"],
    featured: true,
  },
  {
    id: "a-margin-storm",
    slug: "margin-storm",
    title: "Margin Storm",
    artistId: "serre",
    year: "1769",
    medium: "Ground lapis & gold on vellum",
    dimensions: "26 × 19 cm",
    location: "Vellum Room · folio 4",
    collectionId: "manuscripts",
    period: P.court,
    description:
      "A tempest confined entirely to the outer border of a marriage contract, circling the text like weather around a harbour.",
    historicalContext:
      "The lapis ground is unusually thick here, suggesting Serré had access to a rare consignment of the pigment.",
    orientation: "portrait",
    seed: "marginstorm-13",
    palette: { from: "#D9CEA8", via: "#5C6E9A", to: "#20305A", ink: 0.08 },
    alt: "A vellum page whose deep blue and gold border depicts a swirling storm circling a block of formal script.",
    relatedArtworkIds: ["a-tide-charter", "a-silver-fish", "a-reed-hours"],
  },
  {
    id: "a-silver-fish",
    slug: "silver-fish",
    title: "Silver Fish",
    artistId: "serre",
    year: "1774",
    medium: "Silver & gouache on vellum",
    dimensions: "22 × 16 cm",
    location: "Vellum Room · folio 6",
    collectionId: "manuscripts",
    period: P.court,
    description:
      "A shoal of small silvered fish threaded between the lines of a psalm, swimming against the direction of reading.",
    historicalContext:
      "The silver has tarnished to a warm grey, an accident of chemistry the archive has chosen not to reverse.",
    orientation: "portrait",
    seed: "silverfish-14",
    palette: { from: "#E4DAC0", via: "#B4AE96", to: "#6E6A56", ink: 0.05 },
    alt: "A vellum manuscript page with lines of script interwoven with small tarnished-silver fish swimming across the text.",
    relatedArtworkIds: ["a-tide-charter", "a-margin-storm", "a-reed-hours"],
  },
  {
    id: "a-reed-hours",
    slug: "the-reed-hours",
    title: "The Reed Hours",
    artistId: "serre",
    year: "1781",
    medium: "Gold, lapis & lead-white on vellum",
    dimensions: "34 × 24 cm",
    location: "Vellum Room · folio 1",
    collectionId: "manuscripts",
    period: P.court,
    description:
      "A book of hours reworked for the coast, its saints replaced by tides and its calendar by the movement of light.",
    historicalContext:
      "Serré's most ambitious surviving commission, and the closest the manuscripts come to a complete cosmology.",
    orientation: "portrait",
    seed: "reedhours-15",
    palette: { from: "#EBDCB8", via: "#C7A867", to: "#8A6A2E", ink: 0.05 },
    alt: "A richly illuminated book-of-hours page in gold, blue and white depicting tides in place of a religious calendar.",
    relatedArtworkIds: ["a-tide-charter", "a-silver-fish", "a-margin-storm"],
    featured: true,
  },

  // ---- The Indigo Series (Ashcombe / Bann) ----
  {
    id: "a-seventh-dip",
    slug: "the-seventh-dip",
    title: "The Seventh Dip",
    artistId: "ashcombe",
    year: "1789",
    medium: "Indigo on prepared cloth",
    dimensions: "48 × 36 cm",
    location: "Blue Room · rail 2",
    collectionId: "indigo",
    period: P.indigo,
    description:
      "A single field of blue built from seven immersions, the number recorded because the seventh is where it turns to night.",
    historicalContext:
      "Ashcombe and Bann titled works by the count of dye-baths; the practice reads today like a system of musical keys.",
    orientation: "landscape",
    seed: "seventhdip-16",
    palette: { from: "#3F517A", via: "#283656", to: "#141C34", ink: 0.14 },
    alt: "A large deep-blue field of indigo-dyed cloth with subtle tonal variation across seven layered immersions.",
    relatedArtworkIds: ["a-indigo-field", "a-resist-tide", "a-sample-card"],
    featured: true,
  },
  {
    id: "a-indigo-field",
    slug: "indigo-field",
    title: "Indigo Field",
    artistId: "ashcombe",
    year: "1794",
    medium: "Indigo & watercolour",
    dimensions: "40 × 40 cm",
    location: "Blue Room · rail 2",
    collectionId: "indigo",
    period: P.indigo,
    description:
      "The dye-yard seen as landscape — vats and drying cloth reduced to horizontal bands of deepening blue.",
    historicalContext:
      "One of the few Ashcombe works to picture the yards themselves rather than the pure colour they produced.",
    orientation: "square",
    seed: "indigofield-17",
    palette: { from: "#455882", via: "#2B3A5E", to: "#161F3A", ink: 0.12 },
    alt: "A square composition of horizontal blue bands suggesting indigo dye vats and drying cloth in a yard.",
    relatedArtworkIds: ["a-seventh-dip", "a-resist-tide", "a-night-cloth"],
  },
  {
    id: "a-resist-tide",
    slug: "resist-tide",
    title: "Resist / Tide",
    artistId: "ashcombe",
    year: "1801",
    medium: "Resist-dye on cloth",
    dimensions: "52 × 38 cm",
    location: "Blue Room · rail 4",
    collectionId: "indigo",
    period: P.indigo,
    description:
      "Wax-resist patterns that read at once as textile and as the branching channels a tide leaves in sand.",
    historicalContext:
      "The resist technique lets undyed cloth stand for the pale runnels of an ebbing tide.",
    orientation: "landscape",
    seed: "resisttide-18",
    palette: { from: "#3A4C72", via: "#26334F", to: "#101830", ink: 0.13 },
    alt: "A deep blue resist-dyed cloth with pale undyed branching lines resembling tidal channels in sand.",
    relatedArtworkIds: ["a-seventh-dip", "a-indigo-field", "a-tideline"],
  },
  {
    id: "a-night-cloth",
    slug: "night-cloth",
    title: "Night Cloth",
    artistId: "ashcombe",
    year: "1808",
    medium: "Indigo on cloth",
    dimensions: "58 × 42 cm",
    location: "Blue Room · rail 4",
    collectionId: "indigo",
    period: P.indigo,
    description:
      "Blue pushed to its outermost limit, where the dye becomes indistinguishable from black and the cloth from the dark.",
    historicalContext:
      "Often hung beside Vael's Nocturnes to demonstrate two entirely different routes to the same darkness.",
    orientation: "portrait",
    seed: "nightcloth-19",
    palette: { from: "#2A3A5E", via: "#182445", to: "#0A0F1E", ink: 0.18 },
    alt: "A tall panel of indigo cloth dyed so deeply that the blue reads as near-black across most of its surface.",
    relatedArtworkIds: ["a-seventh-dip", "a-black-tide", "a-resist-tide"],
  },
  {
    id: "a-sample-card",
    slug: "sample-card",
    title: "Sample Card",
    artistId: "bann",
    year: "1796",
    medium: "Ground pigment on card",
    dimensions: "30 × 24 cm",
    location: "Colour Room · drawer 1",
    collectionId: "indigo",
    period: P.indigo,
    description:
      "A grid of ground-pigment trials that has outlived its function to become, two centuries on, an abstraction.",
    historicalContext:
      "Bann's working card, never intended as art, now catalogued as one of the school's earliest grids of pure colour.",
    orientation: "portrait",
    seed: "samplecard-20",
    palette: { from: "#C98B5F", via: "#7A6E8A", to: "#2E3A5A", ink: 0.06 },
    alt: "A vertical card divided into a grid of small painted pigment swatches ranging from earth tones to deep blue.",
    relatedArtworkIds: ["a-earth-index", "a-seventh-dip", "a-sand-index"],
  },
  {
    id: "a-earth-index",
    slug: "earth-index",
    title: "Earth Index",
    artistId: "bann",
    year: "1802",
    medium: "Ground mineral on card",
    dimensions: "30 × 24 cm",
    location: "Colour Room · drawer 1",
    collectionId: "indigo",
    period: P.indigo,
    description:
      "A companion card of warm earths — ochre, sienna, umber — each keyed to the cliff it was scraped from.",
    historicalContext:
      "Together with Sample Card it forms the archive's Rosetta stone for identifying pigments across the school.",
    orientation: "portrait",
    seed: "earthindex-21",
    palette: { from: "#D9A46A", via: "#A66A38", to: "#5E381C", ink: 0.06 },
    alt: "A vertical card gridded with warm earth-pigment swatches in ochre, sienna and umber, each hand-labelled.",
    relatedArtworkIds: ["a-sample-card", "a-sand-index", "a-tideline"],
  },

  // ---- Present Tide (Okonkwo) ----
  {
    id: "a-present-tide",
    slug: "present-tide",
    title: "Present Tide",
    artistId: "okonkwo",
    year: "2019",
    medium: "Archival pigment print",
    dimensions: "60 × 90 cm",
    location: "Study Room · print wall",
    collectionId: "present-tide",
    period: P.contemporary,
    description:
      "A photograph of the same flats Marrow painted, made at the same hour, three centuries later.",
    historicalContext:
      "Okonkwo's ongoing rephotography project measures how much — and how little — the Auren light has changed.",
    orientation: "landscape",
    seed: "presenttide-22",
    palette: { from: "#A6C0B2", via: "#67907E", to: "#33564A", ink: 0.05 },
    alt: "A wide contemporary photograph of pale coastal mudflats under soft dawn light, echoing the founding paintings.",
    relatedArtworkIds: ["a-relit", "a-same-quay", "a-tideline"],
    featured: true,
  },
  {
    id: "a-relit",
    slug: "relit",
    title: "Relit",
    artistId: "okonkwo",
    year: "2021",
    medium: "Conservation study & photograph",
    dimensions: "50 × 50 cm",
    location: "Study Room · print wall",
    collectionId: "present-tide",
    period: P.contemporary,
    description:
      "A Vael nocturne photographed under raking conservation light, revealing the figures the dark had swallowed.",
    historicalContext:
      "Part diagnostic image, part homage — the conservator's lamp doing the work of Vael's painted lantern.",
    orientation: "square",
    seed: "relit-23",
    palette: { from: "#8FB0A2", via: "#557E6E", to: "#2A4238", ink: 0.06 },
    alt: "A square photograph of a dark nocturne painting lit from the side, revealing faint hidden figures and ropes.",
    relatedArtworkIds: ["a-present-tide", "a-lantern-quay", "a-same-quay"],
  },
  {
    id: "a-same-quay",
    slug: "the-same-quay",
    title: "The Same Quay",
    artistId: "okonkwo",
    year: "2023",
    medium: "Archival pigment print",
    dimensions: "70 × 50 cm",
    location: "Study Room · print wall",
    collectionId: "present-tide",
    period: P.contemporary,
    description:
      "Vael's quay as it stands now, photographed at the ninth bell, empty of everything but its own long habit of dark.",
    historicalContext:
      "Closes the archive's loop: the founding subject, revisited with the founding attention and modern tools.",
    orientation: "portrait",
    seed: "samequay-24",
    palette: { from: "#7FA294", via: "#4A7062", to: "#26382E", ink: 0.08 },
    alt: "A tall contemporary night photograph of an empty stone quay, quiet and dark, echoing the historical nocturnes.",
    relatedArtworkIds: ["a-present-tide", "a-relit", "a-ninth-bell"],
  },
];
