import type { Artwork } from "./types";

/**
 * =============================================================================
 *  PORTFOLIO PROJECTS  (rendered through the Artwork model)
 * =============================================================================
 *  End-to-end builds — from complete UI design systems to custom full-stack
 *  development and cloud deployment. Each project generates a deterministic
 *  visual from `seed` + `palette` until a real `image` is supplied.
 *  See docs/ASSET_REPLACEMENT.md.
 *
 *  Field mapping for this site:
 *    medium      → stack / deliverables (first token drives the "stack" filter)
 *    dimensions  → project scope
 *    location    → industry · city (text before "·" drives the industry filter)
 *    period      → engagement type
 */

export const artworks: Artwork[] = [
  {
    id: "prj-mindway",
    slug: "mindway-eap",
    title: "Mindway EAP",
    artistId: "team-fullstack",
    year: "2025",
    medium: "React, React Native, Node.js, Cloud",
    dimensions: "Web platform · iOS & Android apps · admin dashboard",
    location: "Employee Wellness · Australia",
    collectionId: "svc-web",
    period: "Platform Build",
    description:
      "A modern digital Employee Assistance Program for an Australian provider — confidential counselling, a personalised wellbeing app, mindfulness and sleep programs, and leadership training, unified across web and native mobile.",
    historicalContext:
      "Traditional EAPs suffer from low engagement, long waits and dated access, so the support goes unused. We built Mindway as one platform: on-demand booking with Australian counsellors, a React Native app for Android and iOS, wellbeing and mindfulness content, an employer admin dashboard, and secure authentication — so help is easy to reach and people actually use it.",
    orientation: "landscape",
    seed: "prj-mindway-07",
    palette: { from: "#7BA3D6", via: "#3A5F8F", to: "#0D1E33", ink: 0.16 },
    image: "/portfolio/mindway.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/mindway.png",
      "/portfolio/mindway-services.png",
      "/portfolio/mindway-industries.png",
      "/portfolio/mindway-about.png",
      "/portfolio/mindway-pricing.png",
    ],
    alt: "Mindway EAP — an Australian Employee Assistance Program platform by GitzTech, spanning a web experience and native iOS and Android apps for confidential counselling and workplace wellbeing.",
    liveUrl: "https://mindwayeap.com.au/",
    appUrl: "https://play.google.com/store/apps/details?id=com.appmindway.mindway&hl=en",
    relatedArtworkIds: ["prj-food", "prj-mockups"],
    featured: true,
  },
  {
    id: "prj-makflip",
    slug: "makflip-marketplace",
    title: "Makflip",
    artistId: "team-fullstack",
    year: "2025",
    medium: "Laravel, Flutter, Multi-Vendor Marketplace",
    dimensions: "Web platform · vendor portal · admin dashboard · mobile apps",
    location: "eCommerce Marketplace · United Kingdom",
    collectionId: "svc-web",
    period: "Platform Build",
    description:
      "A multi-vendor eCommerce marketplace that lets businesses of every size sell groceries, pharmacy items, electronics and more through one centralised platform — with dedicated customer, vendor and admin experiences plus companion mobile apps.",
    historicalContext:
      "Small and medium businesses needed an affordable way to sell online without high marketplace commissions or losing control of their own processes. We built Makflip as a complete marketplace ecosystem: a customer storefront spanning groceries, pharmacy, electronics and more; an independent vendor portal for store, inventory and order management; a marketplace admin dashboard for vendor approvals, promotions and reporting; and companion customer and seller mobile apps — architected to scale from a handful of sellers to thousands.",
    orientation: "landscape",
    seed: "prj-makflip-03",
    palette: { from: "#4E7AB0", via: "#274766", to: "#0B1B2E", ink: 0.16 },
    image: "/portfolio/makflip.jpg",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/makflip.jpg",
      "/portfolio/makflip-home.jpg",
      "/portfolio/makflip-groceries.jpg",
      "/portfolio/makflip-offers.jpg",
    ],
    alt: "Makflip — a multi-vendor eCommerce marketplace platform by GitzTech, spanning a customer storefront, vendor portal, admin dashboard, and mobile apps for grocery, pharmacy, and electronics delivery.",
    liveUrl: "https://www.makflip.com/",
    relatedArtworkIds: ["prj-mindway", "prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-maximalt",
    slug: "maxi-malt",
    title: "Maxi Malt",
    artistId: "team-fullstack",
    year: "2025",
    medium: "Front-End Engineering, Motion & Scroll Animation, eCommerce",
    dimensions: "Brand website · interactive product showcase · eCommerce store",
    location: "Food & Beverage · Consumer Packaged Goods",
    collectionId: "svc-web",
    period: "Platform Build",
    description:
      "An interactive digital home for a heritage malt beverage brand — cinematic product storytelling, scroll-driven animation, and a full direct-to-consumer store built to turn five decades of trust into online sales.",
    historicalContext:
      "A brand with fifty years of heritage needed to compete with today's visually sophisticated beverage sites without losing what made it trusted in the first place. We built Maxi Malt as an animated product journey: cinematic hero moments, an interactive ingredient and nutrition showcase, a heritage story section, and a complete eCommerce flow — catalogue, cart, checkout and subscriptions — so browsing the brand's story leads straight into a purchase.",
    orientation: "landscape",
    seed: "prj-maximalt-04",
    palette: { from: "#FF8F3D", via: "#B85F14", to: "#2E1706", ink: 0.16 },
    image: "/portfolio/maximalt.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/maximalt.png",
      "/portfolio/maximalt-hero.png",
      "/portfolio/maximalt-wordmark.png",
      "/portfolio/maximalt-culture.png",
      "/portfolio/maximalt-vitamins.png",
      "/portfolio/maximalt-editions.png",
      "/portfolio/maximalt-lifestyle.png",
      "/portfolio/maximalt-faq.png",
    ],
    alt: "Maxi Malt — a heritage malt beverage brand website by GitzTech, featuring an interactive product showcase, scroll-driven animation, nutrition storytelling, and an integrated eCommerce store.",
    liveUrl: "https://peachpuff-rail-298897.hostingersite.com/",
    relatedArtworkIds: ["prj-mindway", "prj-makflip", "prj-mockups"],
    featured: true,
  },
  {
    id: "prj-chayah",
    slug: "chayah-villas",
    title: "Chayah Villas",
    artistId: "team-uiux",
    year: "2025",
    medium: "UI/UX Design, Responsive Web Development, SEO",
    dimensions: "Corporate website · property showcase · lead-generation platform",
    location: "Luxury Hospitality & Vacation Rentals · Bali, Indonesia",
    collectionId: "svc-uiux",
    period: "Website Build",
    description:
      "A premium digital showroom for a luxury Bali villa collection — immersive property storytelling, an elegant browsing journey, and conversion-focused design built to turn visitors into qualified booking inquiries.",
    historicalContext:
      "Luxury hospitality has seconds to earn a visitor's trust, so a generic template wasn't an option. We designed Chayah Villas as a lifestyle brand rather than a booking form: cinematic imagery and refined typography carry each villa's story, a curated property showcase lets guests compare stays at a glance, and strategically placed inquiry forms turn that emotional pull into real bookings — all served fast and fully responsive across desktop, tablet and mobile.",
    orientation: "landscape",
    seed: "prj-chayah-02",
    palette: { from: "#FFB870", via: "#B37024", to: "#2E1B08", ink: 0.16 },
    image: "/portfolio/chayah.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/chayah.png",
      "/portfolio/chayah-find.png",
      "/portfolio/chayah-villas.png",
      "/portfolio/chayah-story.png",
      "/portfolio/chayah-why.png",
      "/portfolio/chayah-experiences.png",
    ],
    alt: "Chayah Villas — a luxury Bali villa booking website by GitzTech, showcasing a curated property collection, immersive brand storytelling, and a conversion-focused inquiry journey.",
    liveUrl: "https://darkblue-salamander-438519.hostingersite.com/",
    relatedArtworkIds: ["prj-mindway"],
    featured: true,
  },
  {
    id: "prj-crafting",
    slug: "crafting-studio",
    title: "Crafting Studio",
    artistId: "team-marketers",
    year: "2025",
    medium: "SEO, Paid Social, Email Automation",
    dimensions: "6-month growth programme · 4 channels",
    location: "Arts & Crafts E-Commerce · Lahore",
    collectionId: "svc-marketing",
    period: "Growth Campaign",
    description:
      "A full-funnel growth programme for an arts and crafts store — search, paid social, and lifecycle email working as one system rather than three disconnected budgets.",
    historicalContext:
      "We rebuilt the campaign around contribution margin instead of raw traffic: tightened targeting, rewrote the landing pages, and added abandoned-cart and post-purchase flows. Cost per acquisition fell while repeat-order revenue grew.",
    orientation: "landscape",
    seed: "prj-crafting-02",
    palette: { from: "#FF9807", via: "#B35F00", to: "#2A1500", ink: 0.16 },
    image: "/portfolio/crafting-studio.jpg",
    alt: "Crafting Studio project by GitzTech — a full-funnel digital marketing programme for an arts and crafts e-commerce brand.",
    relatedArtworkIds: ["prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-food",
    slug: "food-supply-co",
    title: "Food Supply Co.",
    artistId: "team-fullstack",
    year: "2025",
    medium: "Next.js, Node.js, PostgreSQL",
    dimensions: "Web app + admin portal · 12 weeks",
    location: "Food Supply Chain · Lahore",
    collectionId: "svc-web",
    period: "Custom Platform",
    description:
      "A custom ordering and logistics platform for a food distributor: live inventory, route-aware delivery windows, and an admin portal the operations team runs the day from.",
    historicalContext:
      "Orders were arriving by phone and WhatsApp and being re-keyed into spreadsheets. We replaced that with a single system — role-based accounts, real-time stock, and automated order confirmations — removing the manual re-entry step entirely.",
    orientation: "landscape",
    seed: "prj-food-03",
    palette: { from: "#2E5C99", via: "#1B3A63", to: "#0B1F3D", ink: 0.18 },
    image: "/portfolio/food-supply-co.jpg",
    alt: "Food Supply Co. project by GitzTech — a custom full-stack ordering and logistics platform for a food supply chain business.",
    relatedArtworkIds: ["prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-wholesale",
    slug: "wholesale-hub",
    title: "Wholesale Hub",
    artistId: "team-ghl",
    year: "2025",
    medium: "GoHighLevel, WhatsApp API, SMS Automation",
    dimensions: "8 funnels · full automation suite",
    location: "Wholesale & B2B · Lahore",
    collectionId: "svc-ghl",
    period: "CRM & Automation",
    description:
      "A GoHighLevel build for a B2B wholesaler: pipelines that match how their reps actually sell, plus WhatsApp and SMS automation that works every lead the moment it lands.",
    historicalContext:
      "Enquiries were being lost between the website form and the sales team's inboxes. We wired a single pipeline with automated follow-up, appointment booking and a WhatsApp chatbot that qualifies leads around the clock — no enquiry now goes unanswered.",
    orientation: "landscape",
    seed: "prj-wholesale-06",
    palette: { from: "#FFB347", via: "#C97A1A", to: "#2E1B05", ink: 0.18 },
    image: "/portfolio/wholesale-hub.jpg",
    alt: "Wholesale Hub project by GitzTech — a GoHighLevel CRM, funnel and WhatsApp automation build for a wholesale B2B business.",
    relatedArtworkIds: ["prj-food", "prj-crafting", "prj-saas-funnel"],
    featured: true,
  },
  {
    id: "prj-thornton",
    slug: "thornton-co",
    title: "Thornton & Co.",
    artistId: "team-uiux",
    year: "2026",
    medium: "Website Design, Wireframes, Prototyping",
    dimensions: "Multi-page responsive website · Figma prototype · booking journey",
    location: "Luxury Fashion & Bespoke Tailoring · London, UK",
    collectionId: "svc-uiux",
    period: "Website Build",
    description:
      "A complete digital experience for a Savile Row bespoke tailoring house — editorial luxury storytelling, dedicated menswear and womenswear service journeys, and a conversion-focused booking flow built to turn craftsmanship into fitting enquiries.",
    historicalContext:
      "Bespoke tailoring can't be sold like ready-to-wear — the value lives in consultation, measurement, fabric and process, not a product grid. We designed Thornton & Co. around a five-stage journey — Discover, Understand, Explore, Trust, Book — giving women's tailoring its own dedicated section rather than a footnote to menswear, reducing the fitting process to four understandable steps, and turning craftsmanship and personalization into scannable, confidence-building content, all leading back to one persistent Book a Fitting conversion.",
    orientation: "landscape",
    seed: "prj-thornton-01",
    palette: { from: "#DED5C8", via: "#A18763", to: "#191917", ink: 0.16 },
    image: "/portfolio/thornton-co.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/thornton-co.png",
      "/portfolio/thornton-co-home.png",
      "/portfolio/thornton-co-services.png",
      "/portfolio/thornton-co-measurements.png",
      "/portfolio/thornton-co-booking.png",
    ],
    alt: "Thornton & Co. — a UI/UX case study for a Savile Row bespoke tailoring website by GitzTech, spanning service discovery, craftsmanship storytelling, personalization, and an appointment-booking journey for both menswear and womenswear.",
    liveUrl: "https://stitcher.gitztech.com/",
    relatedArtworkIds: ["prj-chayah", "prj-parko", "prj-mockups"],
    featured: true,
  },
  {
    id: "prj-parko",
    slug: "parko",
    title: "Parko",
    artistId: "team-uiux",
    year: "2026",
    medium: "Mobile App Design, Wireframes, Prototyping",
    dimensions: "iOS-style mobile app · 10-screen flow · booking & navigation journey",
    location: "Smart Parking / Mobility",
    collectionId: "svc-uiux",
    period: "Mobile App Design",
    description:
      "A smart parking mobile app case study: a dark, premium interface with a single orange accent that takes a driver from nearby discovery through slot reservation, a digital QR ticket, live navigation, and full booking management.",
    historicalContext:
      "Parking is a high-friction, fragmented task — drivers search manually, can't judge trust or safety up front, and lose track of active or cancelled bookings. Parko unifies discovery, reservation, ticketing, navigation, and booking management into one connected mobile flow, built around a component system designed to stay legible and confident on a dark, high-contrast surface.",
    orientation: "portrait",
    seed: "prj-parko-01",
    palette: { from: "#F0B279", via: "#E7872E", to: "#161616", ink: 0.2 },
    image: "/portfolio/parko.jpg",
    imageAspect: "1055 / 1491",
    imageFit: "contain",
    images: ["/portfolio/parko.jpg", "/portfolio/parko-booking.jpg", "/portfolio/parko-ticketing.jpg", "/portfolio/parko-design-system.jpg"],
    alt: "Parko — a UI/UX case study for a smart parking mobile app by GitzTech, spanning nearby discovery, slot selection, a digital QR ticket, live navigation, and a booking management dashboard.",
    relatedArtworkIds: ["prj-thornton", "prj-chayah"],
    featured: true,
  },
  {
    id: "prj-mockups",
    slug: "mockup-designs",
    title: "Mockup Design",
    artistId: "team-uiux",
    year: "2026",
    medium: "Mockups, Presentation Design, Brand Mockups",
    dimensions: "Custom branded compositions · reusable master templates",
    location: "Presentation & Portfolio Design",
    collectionId: "svc-uiux",
    period: "Mockup Design",
    description:
      "Custom, presentation-ready mockups that turn finished websites, apps and digital products into polished visual stories — browser and device compositions built around each project's own brand colors, typography and identity, plus reusable master templates for teams that publish new work often.",
    historicalContext:
      "A screenshot shows what was designed; a mockup shows how the work should be perceived. Rather than dropping every project into the same generic frame, each composition is built from the brand's own colors, type and graphic language — then screens, devices, shadows and hierarchy are refined into a single balanced presentation, exported portfolio-, Behance- and social-ready.",
    orientation: "landscape",
    seed: "prj-mockups-01",
    palette: { from: "#D9B571", via: "#8B6A34", to: "#171310", ink: 0.18 },
    image: "/portfolio/MOCKUPS MAIN.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/MOCKUPS MAIN.png",
      "/portfolio/MOCKUPS (2).png",
      "/portfolio/MOCKUPS (3).png",
      "/portfolio/MOCKUPS (4).png",
    ],
    alt: "Mockup Design — custom, brand-matched presentation mockups by GitzTech for Stitcher/Thornton & Co., Mindway, and Maxi Malt, turning finished websites into portfolio- and Behance-ready visual stories.",
    relatedArtworkIds: ["prj-thornton", "prj-mindway", "prj-maximalt"],
    featured: true,
  },
  {
    id: "prj-saas-funnel",
    slug: "saas-software-funnel",
    title: "SaaS & Software Funnel",
    artistId: "team-ghl",
    year: "2026",
    medium: "GHL, Funnel Design, CRM Automation",
    dimensions: "Multi-section product funnel · demo & appointment booking flow",
    location: "SaaS & Software · B2B Technology",
    collectionId: "svc-ghl",
    period: "CRM & Automation",
    description:
      "A conversion-focused GoHighLevel funnel for SaaS, software, web-app and B2B technology businesses — introducing the product, presenting CRM and AI capability areas, and repeatedly guiding visitors toward a demo, trial, or consultation.",
    historicalContext:
      "SaaS products need to communicate complex value quickly, without overwhelming visitors with technical detail. We built a modular product-marketing structure — value proposition, service capabilities, CRM and AI feature areas, pricing, integrations and social proof — that stays responsive across desktop, tablet and mobile and repeatedly moves visitors toward a demo or appointment.",
    orientation: "landscape",
    seed: "prj-saas-funnel-01",
    palette: { from: "#4FE0B8", via: "#F0873A", to: "#1C1206", ink: 0.16 },
    image: "/portfolio/saas-funnel-hero.jpg",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/saas-funnel-hero.jpg",
      "/portfolio/saas-funnel-solutions.jpg",
      "/portfolio/saas-funnel-crm.jpg",
      "/portfolio/saas-funnel-ai-tools.jpg",
      "/portfolio/saas-funnel-integrations.jpg",
      "/portfolio/saas-funnel.jpg",
    ],
    alt: "SaaS & Software Funnel — a conversion-focused GoHighLevel funnel by GitzTech for SaaS and B2B technology businesses, spanning product value proposition, CRM and AI capability areas, integrations, and a demo/appointment booking flow.",
    relatedArtworkIds: ["prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-leadpilot",
    slug: "leadpilot",
    title: "LeadPilot",
    artistId: "team-fullstack",
    year: "2026",
    medium: "GHL, CRM Dashboard, WhatsApp Automation",
    dimensions: "Lead pipeline dashboard · WhatsApp automation · visual workflow builder",
    location: "CRM & Sales Automation",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A GoHighLevel-style CRM dashboard for managing leads through a visual sales pipeline, with WhatsApp automation and a drag-and-drop workflow builder built in.",
    historicalContext:
      "Sales teams need pipeline visibility and follow-up that doesn't depend on someone remembering to send the next message. LeadPilot tracks every lead through New, Contacted, Proposal and Negotiation stages on one board, while WhatsApp automation and a visual workflow builder handle the follow-up sequencing in the background.",
    orientation: "landscape",
    seed: "prj-leadpilot-01",
    palette: { from: "#8B5FBF", via: "#4A3172", to: "#161225", ink: 0.18 },
    image: "/portfolio/leadpilot.png",
    imageAspect: "713 / 651",
    imageFit: "contain",
    alt: "LeadPilot — a CRM sales-pipeline dashboard project by GitzTech, featuring lead pipeline stages, WhatsApp automation, and a visual workflow builder.",
    relatedArtworkIds: ["prj-b2b-leadgen", "prj-website-rag"],
    featured: true,
  },
  {
    id: "prj-b2b-leadgen",
    slug: "ai-b2b-lead-generation-cold-email-engine",
    title: "AI B2B Lead Generation & Cold Email Engine",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, AI Agents, API Integration",
    dimensions: "6 connected workflows · Google Maps to sales routing",
    location: "Sales Automation / Lead Generation",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A full-cycle B2B outbound engine that sources businesses from Google Maps, extracts and verifies contact data, sends personalized email campaigns, tracks delivery and engagement, classifies replies with AI, triggers follow-ups, and keeps a live CRM-style Google Sheet updated.",
    historicalContext:
      "Manual prospecting, email personalization, reply handling, follow-ups, and CRM updates create fragmented sales operations that are hard to scale. Six connected n8n workflows chain lead discovery, website enrichment, email delivery, webhook-based engagement tracking, AI reply classification, follow-up scheduling, and sales-team routing into one system.",
    orientation: "landscape",
    seed: "prj-b2b-leadgen-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/AI B2B Lead Generation & Cold Email Engine.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "AI B2B Lead Generation & Cold Email Engine — an n8n outbound automation by GitzTech spanning Google Maps lead sourcing, email personalization, AI reply classification, and CRM logging.",
    relatedArtworkIds: ["prj-leadpilot", "prj-video-content-factory"],
    featured: true,
  },
  {
    id: "prj-website-rag",
    slug: "website-to-rag-ai-knowledge-base",
    title: "Website-to-RAG AI Knowledge Base",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, OpenAI Embeddings, Pinecone",
    dimensions: "Crawl → chunk → embed → vector store · RAG-ready knowledge base",
    location: "AI RAG / Knowledge Management",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A reusable system that crawls a website, chunks and embeds its content, stores the knowledge in Pinecone, and prepares it for semantic-search-powered AI conversations.",
    historicalContext:
      "Businesses have valuable information scattered across websites, documentation and marketing pages, but conventional chatbots can't reliably ground answers in that source material. This pipeline automates ingestion from a website into a vector knowledge base — a reusable foundation for support bots, internal search, and product assistants.",
    orientation: "landscape",
    seed: "prj-website-rag-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/Website-to-RAG AI Knowledge Base.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "Website-to-RAG AI Knowledge Base — an n8n pipeline by GitzTech that crawls a website and embeds its content into Pinecone as a semantic-search-ready AI knowledge base.",
    relatedArtworkIds: ["prj-leadpilot", "prj-social-content-engine"],
    featured: false,
  },
  {
    id: "prj-social-content-engine",
    slug: "ai-social-media-content-publishing-engine",
    title: "AI Social Media Content & Publishing Engine",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, AI Content Generation, API Integration",
    dimensions: "Research → draft → human approval → visual generation → publish",
    location: "Marketing Automation / AI Content",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A two-part social media engine that researches high-performing content, analyzes hooks and formats, creates platform-specific content and visuals, then distributes approved content across multiple platforms.",
    historicalContext:
      "Marketing teams spend significant time researching competitors, writing platform-specific posts, creating visuals and publishing content manually. Scheduled research, AI analysis, content generation, human approval and automated multi-platform distribution turn that repeatable process into an operating system.",
    orientation: "landscape",
    seed: "prj-social-content-engine-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/AI Social Media Content & Publishing Engine.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "AI Social Media Content & Publishing Engine — an n8n system by GitzTech that researches, drafts, and publishes platform-specific social content with a human-approval step.",
    relatedArtworkIds: ["prj-website-rag", "prj-ecommerce-assistant"],
    featured: false,
  },
  {
    id: "prj-ecommerce-assistant",
    slug: "ai-ecommerce-operations-assistant-telegram",
    title: "AI eCommerce Operations Assistant via Telegram",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, AI Agents, WooCommerce",
    dimensions: "Telegram interface · AI agent with memory · WooCommerce operations",
    location: "eCommerce / AI Agent / Operations",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A conversational operations assistant that lets WooCommerce teams query orders and products, update product information, log data and trigger notifications from Telegram.",
    historicalContext:
      "Store operators repeatedly switch between the store admin, spreadsheets, email and messaging tools for routine operational tasks. A Telegram interface backed by an AI agent with memory and business tools executes store operations through natural language instead.",
    orientation: "landscape",
    seed: "prj-ecommerce-assistant-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/AI eCommerce Operations Assistant Telegram.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "AI eCommerce Operations Assistant via Telegram — an n8n AI agent by GitzTech letting WooCommerce teams query and update store operations through natural-language Telegram messages.",
    relatedArtworkIds: ["prj-social-content-engine", "prj-recruitment-screening"],
    featured: false,
  },
  {
    id: "prj-recruitment-screening",
    slug: "ai-recruitment-screening-interview-scheduling",
    title: "AI Recruitment Screening & Interview Scheduling on WhatsApp",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, WhatsApp API, AI Screening",
    dimensions: "Candidate screening → qualification → calendar booking → status updates",
    location: "HR Automation / WhatsApp / AI",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A recruitment automation that screens candidates against job criteria, offers interview slots, books meetings, updates hiring status and logs activity.",
    historicalContext:
      "Recruiters lose time on repetitive candidate screening, interview coordination and status communication, especially when applications arrive through messaging channels. WhatsApp becomes an automated candidate journey, with structured records kept in Google Sheets/CRM and qualified candidates scheduled directly into calendars.",
    orientation: "landscape",
    seed: "prj-recruitment-screening-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/AI Screening & Interview Scheduling WhatsApp.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "AI Recruitment Screening & Interview Scheduling on WhatsApp — an n8n automation by GitzTech that screens candidates, books interviews, and updates hiring status over WhatsApp.",
    relatedArtworkIds: ["prj-ecommerce-assistant", "prj-whatsapp-assistant"],
    featured: false,
  },
  {
    id: "prj-whatsapp-assistant",
    slug: "multimodal-whatsapp-personal-ai-assistant",
    title: "Multimodal WhatsApp Personal AI Assistant",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, AI Agents, WhatsApp",
    dimensions: "Text, voice, image & PDF input · 6+ connected business tools",
    location: "AI Agent / WhatsApp / Multimodal",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A WhatsApp-based personal assistant that accepts text, voice, images and PDFs, then uses connected tools for Gmail, Calendar, Drive, Airtable, web search and messaging.",
    historicalContext:
      "Users want a single conversational interface for tasks that normally require switching between email, calendar, files, contacts and web tools. Multiple input types are normalized into a common AI-agent interface with context and real tool-calling capability across a business's actual software stack.",
    orientation: "landscape",
    seed: "prj-whatsapp-assistant-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/Multimodal WhatsApp Personal AI Assistant.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "Multimodal WhatsApp Personal AI Assistant — an n8n AI agent by GitzTech accepting text, voice, image and PDF input over WhatsApp, connected to Gmail, Calendar, Drive and Airtable.",
    relatedArtworkIds: ["prj-recruitment-screening", "prj-voice-receptionist"],
    featured: false,
  },
  {
    id: "prj-voice-receptionist",
    slug: "ai-voice-receptionist-factory",
    title: "AI Voice Receptionist Factory for Local Businesses",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, Claude, VAPI",
    dimensions: "Business discovery → website analysis → prompt generation → voice deployment",
    location: "Voice AI / Lead Generation / Agency Automation",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "An agency-oriented automation that discovers local businesses, analyzes their websites, generates tailored voice-agent prompts, and deploys AI receptionist agents through VAPI.",
    historicalContext:
      "AI voice agencies can spend significant time researching each business and manually configuring a unique receptionist prompt and deployment. This pipeline automates the entire provisioning path — from local-business discovery through website analysis, prompt generation and voice-agent deployment.",
    orientation: "landscape",
    seed: "prj-voice-receptionist-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/AI Voice Receptionist for Local Businesses.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "AI Voice Receptionist Factory for Local Businesses — an n8n and Claude pipeline by GitzTech that discovers local businesses and deploys tailored AI voice receptionists through VAPI.",
    relatedArtworkIds: ["prj-whatsapp-assistant", "prj-video-content-factory"],
    featured: false,
  },
  {
    id: "prj-video-content-factory",
    slug: "ai-video-content-multi-platform-publishing",
    title: "AI Video Content & Multi-Platform Publishing",
    artistId: "team-fullstack",
    year: "2026",
    medium: "n8n, Google Veo3, Blotato",
    dimensions: "Daily AI script → Veo3 render → 8-platform auto-publish",
    location: "AI Video / Content Automation / Social Publishing",
    collectionId: "svc-web",
    period: "AI Automation",
    description:
      "A visual content factory that generates ideas and scripts, creates video prompts, renders videos with Veo3, stores outputs and automatically distributes the finished videos across major social networks.",
    historicalContext:
      "Short-form video production requires ideation, scripting, prompt engineering, rendering, file handling and multi-platform publishing — each step adding operational overhead. AI ideation, script generation, Veo3 video creation, asset tracking and multi-platform publishing chain into one scheduled content pipeline.",
    orientation: "landscape",
    seed: "prj-video-content-factory-01",
    palette: { from: "#F0B429", via: "#2E4C8A", to: "#0A1327", ink: 0.18 },
    image: "/portfolio/AI Video Content & Multi-Platform Publishing.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    alt: "AI Video Content & Multi-Platform Publishing — an n8n pipeline by GitzTech that scripts, renders with Veo3, and auto-publishes short-form video across eight social platforms.",
    relatedArtworkIds: ["prj-voice-receptionist", "prj-b2b-leadgen"],
    featured: false,
  },
];
