import type { Artwork } from "./types";

/**
 * =============================================================================
 *  PORTFOLIO PROJECTS  (rendered through the Artwork model)
 * =============================================================================
 *  End-to-end builds — from complete UI design systems to custom full-stack
 *  development and cloud deployment. Each project generates a deterministic
 *  visual from `seed` + `palette` until a real `image` is supplied.
 *  See docs/ASSET_REPLACEMENT.md.
 *
 *  Field mapping for this site:
 *    medium      → stack / deliverables (first token drives the "stack" filter)
 *    dimensions  → project scope
 *    location    → industry · city (text before "·" drives the industry filter)
 *    period      → engagement type
 */

export const artworks: Artwork[] = [
  {
    id: "prj-mindway",
    slug: "mindway-eap",
    title: "Mindway EAP",
    artistId: "team-fullstack",
    year: "2025",
    medium: "React, React Native, Node.js, Cloud",
    dimensions: "Web platform · iOS & Android apps · admin dashboard",
    location: "Employee Wellness · Australia",
    collectionId: "svc-web",
    period: "Platform Build",
    description:
      "A modern digital Employee Assistance Program for an Australian provider — confidential counselling, a personalised wellbeing app, mindfulness and sleep programs, and leadership training, unified across web and native mobile.",
    historicalContext:
      "Traditional EAPs suffer from low engagement, long waits and dated access, so the support goes unused. We built Mindway as one platform: on-demand booking with Australian counsellors, a React Native app for Android and iOS, wellbeing and mindfulness content, an employer admin dashboard, and secure authentication — so help is easy to reach and people actually use it.",
    orientation: "landscape",
    seed: "prj-mindway-07",
    palette: { from: "#7BA3D6", via: "#3A5F8F", to: "#0D1E33", ink: 0.16 },
    image: "/portfolio/mindway.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/mindway.png",
      "/portfolio/mindway-services.png",
      "/portfolio/mindway-industries.png",
      "/portfolio/mindway-about.png",
      "/portfolio/mindway-pricing.png",
    ],
    alt: "Mindway EAP — an Australian Employee Assistance Program platform by GitzTech, spanning a web experience and native iOS and Android apps for confidential counselling and workplace wellbeing.",
    liveUrl: "https://mindwayeap.com.au/",
    appUrl: "https://play.google.com/store/apps/details?id=com.appmindway.mindway&hl=en",
    relatedArtworkIds: ["prj-food", "prj-mockups"],
    featured: true,
  },
  {
    id: "prj-makflip",
    slug: "makflip-marketplace",
    title: "Makflip",
    artistId: "team-fullstack",
    year: "2025",
    medium: "Laravel, Flutter, Multi-Vendor Marketplace",
    dimensions: "Web platform · vendor portal · admin dashboard · mobile apps",
    location: "eCommerce Marketplace · United Kingdom",
    collectionId: "svc-web",
    period: "Platform Build",
    description:
      "A multi-vendor eCommerce marketplace that lets businesses of every size sell groceries, pharmacy items, electronics and more through one centralised platform — with dedicated customer, vendor and admin experiences plus companion mobile apps.",
    historicalContext:
      "Small and medium businesses needed an affordable way to sell online without high marketplace commissions or losing control of their own processes. We built Makflip as a complete marketplace ecosystem: a customer storefront spanning groceries, pharmacy, electronics and more; an independent vendor portal for store, inventory and order management; a marketplace admin dashboard for vendor approvals, promotions and reporting; and companion customer and seller mobile apps — architected to scale from a handful of sellers to thousands.",
    orientation: "landscape",
    seed: "prj-makflip-03",
    palette: { from: "#4E7AB0", via: "#274766", to: "#0B1B2E", ink: 0.16 },
    image: "/portfolio/makflip.jpg",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/makflip.jpg",
      "/portfolio/makflip-home.jpg",
      "/portfolio/makflip-groceries.jpg",
      "/portfolio/makflip-offers.jpg",
    ],
    alt: "Makflip — a multi-vendor eCommerce marketplace platform by GitzTech, spanning a customer storefront, vendor portal, admin dashboard, and mobile apps for grocery, pharmacy, and electronics delivery.",
    liveUrl: "https://www.makflip.com/",
    relatedArtworkIds: ["prj-mindway", "prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-maximalt",
    slug: "maxi-malt",
    title: "Maxi Malt",
    artistId: "team-fullstack",
    year: "2025",
    medium: "Front-End Engineering, Motion & Scroll Animation, eCommerce",
    dimensions: "Brand website · interactive product showcase · eCommerce store",
    location: "Food & Beverage · Consumer Packaged Goods",
    collectionId: "svc-web",
    period: "Platform Build",
    description:
      "An interactive digital home for a heritage malt beverage brand — cinematic product storytelling, scroll-driven animation, and a full direct-to-consumer store built to turn five decades of trust into online sales.",
    historicalContext:
      "A brand with fifty years of heritage needed to compete with today's visually sophisticated beverage sites without losing what made it trusted in the first place. We built Maxi Malt as an animated product journey: cinematic hero moments, an interactive ingredient and nutrition showcase, a heritage story section, and a complete eCommerce flow — catalogue, cart, checkout and subscriptions — so browsing the brand's story leads straight into a purchase.",
    orientation: "landscape",
    seed: "prj-maximalt-04",
    palette: { from: "#FF8F3D", via: "#B85F14", to: "#2E1706", ink: 0.16 },
    image: "/portfolio/maximalt.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/maximalt.png",
      "/portfolio/maximalt-hero.png",
      "/portfolio/maximalt-wordmark.png",
      "/portfolio/maximalt-culture.png",
      "/portfolio/maximalt-vitamins.png",
      "/portfolio/maximalt-editions.png",
      "/portfolio/maximalt-lifestyle.png",
      "/portfolio/maximalt-faq.png",
    ],
    alt: "Maxi Malt — a heritage malt beverage brand website by GitzTech, featuring an interactive product showcase, scroll-driven animation, nutrition storytelling, and an integrated eCommerce store.",
    liveUrl: "https://peachpuff-rail-298897.hostingersite.com/",
    relatedArtworkIds: ["prj-mindway", "prj-makflip", "prj-mockups"],
    featured: true,
  },
  {
    id: "prj-chayah",
    slug: "chayah-villas",
    title: "Chayah Villas",
    artistId: "team-uiux",
    year: "2025",
    medium: "UI/UX Design, Responsive Web Development, SEO",
    dimensions: "Corporate website · property showcase · lead-generation platform",
    location: "Luxury Hospitality & Vacation Rentals · Bali, Indonesia",
    collectionId: "svc-uiux",
    period: "Website Build",
    description:
      "A premium digital showroom for a luxury Bali villa collection — immersive property storytelling, an elegant browsing journey, and conversion-focused design built to turn visitors into qualified booking inquiries.",
    historicalContext:
      "Luxury hospitality has seconds to earn a visitor's trust, so a generic template wasn't an option. We designed Chayah Villas as a lifestyle brand rather than a booking form: cinematic imagery and refined typography carry each villa's story, a curated property showcase lets guests compare stays at a glance, and strategically placed inquiry forms turn that emotional pull into real bookings — all served fast and fully responsive across desktop, tablet and mobile.",
    orientation: "landscape",
    seed: "prj-chayah-02",
    palette: { from: "#FFB870", via: "#B37024", to: "#2E1B08", ink: 0.16 },
    image: "/portfolio/chayah.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/chayah.png",
      "/portfolio/chayah-find.png",
      "/portfolio/chayah-villas.png",
      "/portfolio/chayah-story.png",
      "/portfolio/chayah-why.png",
      "/portfolio/chayah-experiences.png",
    ],
    alt: "Chayah Villas — a luxury Bali villa booking website by GitzTech, showcasing a curated property collection, immersive brand storytelling, and a conversion-focused inquiry journey.",
    liveUrl: "https://darkblue-salamander-438519.hostingersite.com/",
    relatedArtworkIds: ["prj-mindway"],
    featured: true,
  },
  {
    id: "prj-crafting",
    slug: "crafting-studio",
    title: "Crafting Studio",
    artistId: "team-marketers",
    year: "2025",
    medium: "SEO, Paid Social, Email Automation",
    dimensions: "6-month growth programme · 4 channels",
    location: "Arts & Crafts E-Commerce · Lahore",
    collectionId: "svc-marketing",
    period: "Growth Campaign",
    description:
      "A full-funnel growth programme for an arts and crafts store — search, paid social, and lifecycle email working as one system rather than three disconnected budgets.",
    historicalContext:
      "We rebuilt the campaign around contribution margin instead of raw traffic: tightened targeting, rewrote the landing pages, and added abandoned-cart and post-purchase flows. Cost per acquisition fell while repeat-order revenue grew.",
    orientation: "landscape",
    seed: "prj-crafting-02",
    palette: { from: "#FF9807", via: "#B35F00", to: "#2A1500", ink: 0.16 },
    image: "/portfolio/crafting-studio.jpg",
    alt: "Crafting Studio project by GitzTech — a full-funnel digital marketing programme for an arts and crafts e-commerce brand.",
    relatedArtworkIds: ["prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-food",
    slug: "food-supply-co",
    title: "Food Supply Co.",
    artistId: "team-fullstack",
    year: "2025",
    medium: "Next.js, Node.js, PostgreSQL",
    dimensions: "Web app + admin portal · 12 weeks",
    location: "Food Supply Chain · Lahore",
    collectionId: "svc-web",
    period: "Custom Platform",
    description:
      "A custom ordering and logistics platform for a food distributor: live inventory, route-aware delivery windows, and an admin portal the operations team runs the day from.",
    historicalContext:
      "Orders were arriving by phone and WhatsApp and being re-keyed into spreadsheets. We replaced that with a single system — role-based accounts, real-time stock, and automated order confirmations — removing the manual re-entry step entirely.",
    orientation: "landscape",
    seed: "prj-food-03",
    palette: { from: "#2E5C99", via: "#1B3A63", to: "#0B1F3D", ink: 0.18 },
    image: "/portfolio/food-supply-co.jpg",
    alt: "Food Supply Co. project by GitzTech — a custom full-stack ordering and logistics platform for a food supply chain business.",
    relatedArtworkIds: ["prj-wholesale"],
    featured: true,
  },
  {
    id: "prj-stitcher",
    slug: "stitcher",
    title: "Stitcher",
    artistId: "team-uiux",
    year: "2024",
    medium: "Brand Identity, Logo System, Social Creative",
    dimensions: "Full identity · print + digital kit",
    location: "Fashion & Tailoring · Lahore",
    collectionId: "svc-graphic",
    period: "Brand Identity",
    description:
      "A complete brand identity for a bespoke tailoring house — a mark, type system and creative kit that reads as precise and made-to-measure across every touchpoint.",
    historicalContext:
      "The business had grown through word of mouth with no consistent visual language. We built the identity from its positioning — craft and precision — and delivered templates the team runs themselves for social, packaging and print.",
    orientation: "landscape",
    seed: "prj-stitcher-05",
    palette: { from: "#8FA9D6", via: "#3D5580", to: "#101B30", ink: 0.16 },
    image: "/portfolio/stitcher.jpg",
    alt: "Stitcher project by GitzTech — a complete brand identity and creative system for a fashion and tailoring house.",
    relatedArtworkIds: ["prj-thornton"],
    featured: true,
  },
  {
    id: "prj-wholesale",
    slug: "wholesale-hub",
    title: "Wholesale Hub",
    artistId: "team-ghl",
    year: "2025",
    medium: "GoHighLevel, WhatsApp API, SMS Automation",
    dimensions: "8 funnels · full automation suite",
    location: "Wholesale & B2B · Lahore",
    collectionId: "svc-ghl",
    period: "CRM & Automation",
    description:
      "A GoHighLevel build for a B2B wholesaler: pipelines that match how their reps actually sell, plus WhatsApp and SMS automation that works every lead the moment it lands.",
    historicalContext:
      "Enquiries were being lost between the website form and the sales team's inboxes. We wired a single pipeline with automated follow-up, appointment booking and a WhatsApp chatbot that qualifies leads around the clock — no enquiry now goes unanswered.",
    orientation: "landscape",
    seed: "prj-wholesale-06",
    palette: { from: "#FFB347", via: "#C97A1A", to: "#2E1B05", ink: 0.18 },
    image: "/portfolio/wholesale-hub.jpg",
    alt: "Wholesale Hub project by GitzTech — a GoHighLevel CRM, funnel and WhatsApp automation build for a wholesale B2B business.",
    relatedArtworkIds: ["prj-food", "prj-crafting", "prj-saas-funnel"],
    featured: true,
  },
  {
    id: "prj-thornton",
    slug: "thornton-co",
    title: "Thornton & Co.",
    artistId: "team-uiux",
    year: "2026",
    medium: "Website Design, Wireframes, Prototyping",
    dimensions: "Multi-page responsive website · Figma prototype · booking journey",
    location: "Luxury Fashion & Bespoke Tailoring · London, UK",
    collectionId: "svc-uiux",
    period: "Website Build",
    description:
      "A complete digital experience for a Savile Row bespoke tailoring house — editorial luxury storytelling, dedicated menswear and womenswear service journeys, and a conversion-focused booking flow built to turn craftsmanship into fitting enquiries.",
    historicalContext:
      "Bespoke tailoring can't be sold like ready-to-wear — the value lives in consultation, measurement, fabric and process, not a product grid. We designed Thornton & Co. around a five-stage journey — Discover, Understand, Explore, Trust, Book — giving women's tailoring its own dedicated section rather than a footnote to menswear, reducing the fitting process to four understandable steps, and turning craftsmanship and personalization into scannable, confidence-building content, all leading back to one persistent Book a Fitting conversion.",
    orientation: "landscape",
    seed: "prj-thornton-01",
    palette: { from: "#DED5C8", via: "#A18763", to: "#191917", ink: 0.16 },
    image: "/portfolio/thornton-co.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/thornton-co.png",
      "/portfolio/thornton-co-home.png",
      "/portfolio/thornton-co-services.png",
      "/portfolio/thornton-co-measurements.png",
      "/portfolio/thornton-co-booking.png",
    ],
    alt: "Thornton & Co. — a UI/UX case study for a Savile Row bespoke tailoring website by GitzTech, spanning service discovery, craftsmanship storytelling, personalization, and an appointment-booking journey for both menswear and womenswear.",
    liveUrl: "https://stitcher.gitztech.com/",
    relatedArtworkIds: ["prj-chayah", "prj-parko", "prj-mockups"],
    featured: true,
  },
  {
    id: "prj-parko",
    slug: "parko",
    title: "Parko",
    artistId: "team-uiux",
    year: "2026",
    medium: "Mobile App Design, Wireframes, Prototyping",
    dimensions: "iOS-style mobile app · 10-screen flow · booking & navigation journey",
    location: "Smart Parking / Mobility",
    collectionId: "svc-uiux",
    period: "Mobile App Design",
    description:
      "A smart parking mobile app case study: a dark, premium interface with a single orange accent that takes a driver from nearby discovery through slot reservation, a digital QR ticket, live navigation, and full booking management.",
    historicalContext:
      "Parking is a high-friction, fragmented task — drivers search manually, can't judge trust or safety up front, and lose track of active or cancelled bookings. Parko unifies discovery, reservation, ticketing, navigation, and booking management into one connected mobile flow, built around a component system designed to stay legible and confident on a dark, high-contrast surface.",
    orientation: "portrait",
    seed: "prj-parko-01",
    palette: { from: "#F0B279", via: "#E7872E", to: "#161616", ink: 0.2 },
    image: "/portfolio/parko.jpg",
    imageAspect: "1055 / 1491",
    imageFit: "contain",
    images: ["/portfolio/parko.jpg", "/portfolio/parko-booking.jpg", "/portfolio/parko-ticketing.jpg", "/portfolio/parko-design-system.jpg"],
    alt: "Parko — a UI/UX case study for a smart parking mobile app by GitzTech, spanning nearby discovery, slot selection, a digital QR ticket, live navigation, and a booking management dashboard.",
    relatedArtworkIds: ["prj-thornton", "prj-chayah"],
    featured: true,
  },
  {
    id: "prj-mockups",
    slug: "mockup-designs",
    title: "Mockup Design",
    artistId: "team-uiux",
    year: "2026",
    medium: "Mockups, Presentation Design, Brand Mockups",
    dimensions: "Custom branded compositions · reusable master templates",
    location: "Presentation & Portfolio Design",
    collectionId: "svc-uiux",
    period: "Mockup Design",
    description:
      "Custom, presentation-ready mockups that turn finished websites, apps and digital products into polished visual stories — browser and device compositions built around each project's own brand colors, typography and identity, plus reusable master templates for teams that publish new work often.",
    historicalContext:
      "A screenshot shows what was designed; a mockup shows how the work should be perceived. Rather than dropping every project into the same generic frame, each composition is built from the brand's own colors, type and graphic language — then screens, devices, shadows and hierarchy are refined into a single balanced presentation, exported portfolio-, Behance- and social-ready.",
    orientation: "landscape",
    seed: "prj-mockups-01",
    palette: { from: "#D9B571", via: "#8B6A34", to: "#171310", ink: 0.18 },
    image: "/portfolio/MOCKUPS MAIN.png",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/MOCKUPS MAIN.png",
      "/portfolio/MOCKUPS (2).png",
      "/portfolio/MOCKUPS (3).png",
      "/portfolio/MOCKUPS (4).png",
    ],
    alt: "Mockup Design — custom, brand-matched presentation mockups by GitzTech for Stitcher/Thornton & Co., Mindway, and Maxi Malt, turning finished websites into portfolio- and Behance-ready visual stories.",
    relatedArtworkIds: ["prj-thornton", "prj-mindway", "prj-maximalt"],
    featured: true,
  },
  {
    id: "prj-saas-funnel",
    slug: "saas-software-funnel",
    title: "SaaS & Software Funnel",
    artistId: "team-ghl",
    year: "2026",
    medium: "GHL, Funnel Design, CRM Automation",
    dimensions: "Multi-section product funnel · demo & appointment booking flow",
    location: "SaaS & Software · B2B Technology",
    collectionId: "svc-ghl",
    period: "CRM & Automation",
    description:
      "A conversion-focused GoHighLevel funnel for SaaS, software, web-app and B2B technology businesses — introducing the product, presenting CRM and AI capability areas, and repeatedly guiding visitors toward a demo, trial, or consultation.",
    historicalContext:
      "SaaS products need to communicate complex value quickly, without overwhelming visitors with technical detail. We built a modular product-marketing structure — value proposition, service capabilities, CRM and AI feature areas, pricing, integrations and social proof — that stays responsive across desktop, tablet and mobile and repeatedly moves visitors toward a demo or appointment.",
    orientation: "landscape",
    seed: "prj-saas-funnel-01",
    palette: { from: "#4FE0B8", via: "#F0873A", to: "#1C1206", ink: 0.16 },
    image: "/portfolio/saas-funnel-hero.jpg",
    imageAspect: "4 / 3",
    imageFit: "contain",
    images: [
      "/portfolio/saas-funnel-hero.jpg",
      "/portfolio/saas-funnel-solutions.jpg",
      "/portfolio/saas-funnel-crm.jpg",
      "/portfolio/saas-funnel-ai-tools.jpg",
      "/portfolio/saas-funnel-integrations.jpg",
      "/portfolio/saas-funnel.jpg",
    ],
    alt: "SaaS & Software Funnel — a conversion-focused GoHighLevel funnel by GitzTech for SaaS and B2B technology businesses, spanning product value proposition, CRM and AI capability areas, integrations, and a demo/appointment booking flow.",
    relatedArtworkIds: ["prj-wholesale"],
    featured: true,
  },
];
