import type { TimelineEntry } from "./types";

/** PLACEHOLDER CONTENT — invented chronology for demonstration. */
export const timeline: TimelineEntry[] = [
  {
    id: "t-1719",
    year: "1719",
    title: "Marrow leaves the drafting table",
    body: "Isolde Marrow abandons her post as a mapmaker's assistant and begins painting the tidal flats north of Saltmeadow at first and last light.",
    location: "Saltmeadow",
    collectionId: "luminist",
  },
  {
    id: "t-1731",
    year: "1731",
    title: "The Tideline",
    body: "The earliest surviving Marrow panel establishes the compressed, horizontal format that will define the founding luminists.",
    location: "Saltmeadow",
    collectionId: "luminist",
  },
  {
    id: "t-1759",
    year: "1759",
    title: "Lantern on the Quay",
    body: "Caspian Vael completes the keystone of the Nocturnes, built from more than thirty lamp-black glazes cured across a full year.",
    location: "Old Customs House",
    collectionId: "nocturnes",
  },
  {
    id: "t-1762",
    year: "1762",
    title: "Serré illuminates the Tide Charter",
    body: "Ondine Serré's marginal weather begins to overwhelm the official documents of the Reed Court.",
    location: "The Reed Court",
    collectionId: "manuscripts",
  },
  {
    id: "t-1781",
    year: "1781",
    title: "The Reed Hours",
    body: "Serré's most ambitious commission reworks the book of hours for the coast, replacing saints with tides.",
    location: "The Reed Court",
    collectionId: "manuscripts",
  },
  {
    id: "t-1783",
    year: "1783",
    title: "The Ninth Bell",
    body: "Vael's final nocturne pushes darkness to its limit; conservators now believe the near-total black is intentional.",
    location: "Old Customs House",
    collectionId: "nocturnes",
  },
  {
    id: "t-1789",
    year: "1789",
    title: "The Seventh Dip",
    body: "Mireille Ashcombe and Aurelio Bann formalise the practice of titling works by their count of indigo immersions.",
    location: "The Dye Yards",
    collectionId: "indigo",
  },
  {
    id: "t-1796",
    year: "1796",
    title: "Bann's Sample Card",
    body: "Aurelio Bann's working pigment grids, never intended as art, are later catalogued among the school's earliest abstractions.",
    location: "Colour Room",
    collectionId: "indigo",
  },
  {
    id: "t-1804",
    year: "1804",
    title: "Survey, in Haze",
    body: "Thomas Reyne begins overlaying his triangulation lines with wet washes, blurring the border between measurement and mood.",
    location: "Map Room",
    collectionId: "luminist",
  },
  {
    id: "t-1819",
    year: "1819",
    title: "Estuary",
    body: "Reyne's late watercolours abandon the coastline entirely — the bridge between the founding school and the modern archive.",
    location: "Map Room",
    collectionId: "luminist",
  },
  {
    id: "t-2009",
    year: "2009",
    title: "Okonkwo takes custody",
    body: "Livia Okonkwo begins directing conservation of the Auren holdings and authoring the modern catalogue.",
    location: "The Auren Archive",
    collectionId: "present-tide",
  },
  {
    id: "t-2023",
    year: "2023",
    title: "The Same Quay",
    body: "Okonkwo photographs Vael's quay at the ninth bell, closing the archive's three-century loop.",
    location: "Old Customs House",
    collectionId: "present-tide",
  },
];
